apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: irsa-auditor-role-binding
subjects:
- kind: ServiceAccount
  name: irsa-auditor-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: irsa-auditor-role
  apiGroup: rbac.authorization.k8s.io